### ISSUE TITLE
module node-win-x86/package.json not found

### ISSUE THREAD

**Issue by ekoeryanto** [zkat/npx#187]
fail when running `npx node@xx command` with arch x86 (throwing above message), 
but success on x64 arch.

here is my appveyor config
```yml
environment:
  matrix:
    - node_arch: "x64"
install:
  - ps: Install-Product node 10 $env:node_arch
  - set PATH=%APPDATA%\npm;%PATH%
  - npx >nul 2>&1 || ( npm install --silent --global npx )
  - npm install
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - rem *********** Using node 10 ***********
  - npx -p node@10 npm rebuild >nul 2>&1
  - npx -p node@10 jest --ci

  - rem *********** Using node 8 ***********
  - npx -p node@8 npm rebuild >nul 2>&1
  - npx -p node@8 jest --ci

  - rem *********** Using node 6 ***********
  - npx -p node@6 npm rebuild >nul 2>&1
  - npx -p node@6 jest --ci

  - rem *********** Using node 4 ***********
  - npx -p node@4 npm rebuild >nul 2>&1
  - npx -p node@4 jest --ci --env=node

cache:
  - node_modules
  - '%AppData%/npm-cache'
  - '%AppData%/npm'
```
